version: '1.0'
steps:
  clone:
    title: Cloning repository
    type: git-clone
    repo: 'https://github.com/titukhan2000/SampleCore5'
    revision: dockerfile-change
    stage: clone
  build_my_app:
    title: Net5 Image
    type: build
    stage: build
    image_name: CCountNet
    working_directory: '${{clone}}'
    tag: master
    disable_push: true
    dockerfile: Dockerfile
  push_to_my_registry:
    type: parallel
    stage: push
    steps:
      pushing_to_docker:
        type: push
        title: Pushing to a registry
        candidate: '${{build_my_app}}'
        tag: v1.0.0
        registry: CodeFreshRegistry
        image_name: devilsdocker/cccount
stages:
  - clone
  - build
  - push
